name: onesync
on:
  schedule:
   - cron: 0 12 * * *
  workflow_dispatch:
    inputs:
    
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Courses 3 - Oned A
    steps:
      - uses: actions/checkout@v2
      - name: rclone Install
        run: |
          curl https://rclone.org/install.sh | sudo bash
      - name: rclone Config
        run: |
          mkdir -p ~/.config/rclone
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONFIG }}
          EOF
      - name: rclone Run
        run: |
          rclone copy course3:/ oneda:/ -P --check-first --checkers 256 --stats-one-line --stats=1s --transfers 8 --onedrive-chunk-size 60M --drive-chunk-size 128M --drive-acknowledge-abuse --onedrive-no-versions
